version: '3.3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db
    ports:
      - '27017:27017'
    volumes:
      - './mongo/data:/data/db'
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '15672:15672'
  server:
    build: ./server
    image: server:latest
    ports:
      - '8080:5000'
    volumes:
      - './server:/app'
    environment:
       MONGO_HOST: mongo
       MONGO_PORT: 27017
       MONGO_USER: root
       MONGO_PASSWORD: root
       MONGO_DB: admin
       FLASK_ENV: development
  document-server:
    build: ./document-server
    image: document-server:latest
    ports:
      - '8081:3000'
    volumes:
      - './document-server:/app'
  client:
    build: ./client
    image: client:latest
    ports:
      - '80:3000'
    volumes:
      - './client:/app'
