version: '3.3'
services:
  server:
    build: ./server
    image: server:latest
    ports:
      - '8080:5000'
    volumes:
      - './server:/app'
  client:
    build: ./client
    image: client:latest
    ports:
      - '8000:3000'
    volumes:
      - './client:/app'